# Shared by the writer and the reader units. They are built separately because
# they are published under different providers, but both take their sources
# from here so that the type support cannot drift between them.

set(RTPS_SRC_DIR "${CMAKE_CURRENT_LIST_DIR}")

find_package(fastcdr 2 REQUIRED)
find_package(fastdds 3 REQUIRED)

# Type support generated by fastddsgen upstream and vendored next to the
# sources, so building this needs no code generator.
file(GLOB RTPS_TYPE_SOURCES "${RTPS_SRC_DIR}/*.cxx")

function(add_rtps_service role)
    add_executable(rtps-${role} "${RTPS_SRC_DIR}/${role}.cpp" ${RTPS_TYPE_SOURCES})

    target_include_directories(rtps-${role} PRIVATE "${RTPS_SRC_DIR}")
    target_link_libraries(rtps-${role} fastdds fastcdr)

    install(TARGETS rtps-${role} RUNTIME DESTINATION rootfs)
endfunction()
