schemaVersion: 2

publisher:
  author: Developer Name
  company: Company Name

publish:
  tlsKey: aos-user-sp.p12

items:
  ##############################################################################
  # Demo load test service 1
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-1
    title: Demo Load Test Service 1
    description: Demo service for load testing (service1)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 2
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-2
    title: Demo Load Test Service 2
    description: Demo service for load testing (service2)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 3
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-3
    title: Demo Load Test Service 3
    description: Demo service for load testing (service3)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 4
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-4
    title: Demo Load Test Service 4
    description: Demo service for load testing (service4)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 5
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-5
    title: Demo Load Test Service 5
    description: Demo service for load testing (service5)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 6
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-6
    title: Demo Load Test Service 6
    description: Demo service for load testing (service6)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 7
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-7
    title: Demo Load Test Service 7
    description: Demo service for load testing (service7)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 8
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-8
    title: Demo Load Test Service 8
    description: Demo service for load testing (service8)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 9
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-9
    title: Demo Load Test Service 9
    description: Demo service for load testing (service9)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 10
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-10
    title: Demo Load Test Service 10
    description: Demo service for load testing (service10)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 11
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-11
    title: Demo Load Test Service 11
    description: Demo service for load testing (service11)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 12
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-12
    title: Demo Load Test Service 12
    description: Demo service for load testing (service12)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 13
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-13
    title: Demo Load Test Service 13
    description: Demo service for load testing (service13)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 14
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-14
    title: Demo Load Test Service 14
    description: Demo service for load testing (service14)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 15
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-15
    title: Demo Load Test Service 15
    description: Demo service for load testing (service15)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 16
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB

  ##############################################################################
  # Demo load test service 16
  ##############################################################################
- identity:
    type: service
    codename: demo-load-test-service-16
    title: Demo Load Test Service 16
    description: Demo service for load testing (service16)

  version: 1.0.0-beta.1
  sourceFolder: output
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64

  configuration:
    workingDir: /
    cmd: /load-test
    instances:
      minInstances: 12
      priority: 0

    skipResourceLimits: true
    quotas:
      cpuLimit: 200
      ramLimit: 2MiB
