schemaVersion: 2
publisher:
  author: Developer Name
  company: Company Name
publish:
  tlsKey: aos-user-sp.p12
items:
- identity:
    type: service
    codename: demo-hello-world-cpp
    title: Demo Hello World C++
    description: Simple C++ Hello World service
  version: 2.0.0
  sourceFolder: service
  images:
  - sourceFolder: x86
    archInfo:
      architecture: amd64
  configuration:
    workingDir: /
    cmd: ./hello_world
    instances:
      minInstances: 1
    quotas:
      cpuLimit: 1000
      ramLimit: 128MiB
      storageLimit: 32MiB
